# Generated by Django 4.0.2 on 2022-02-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('base_currency', models.CharField(default='usd', max_length=255)),
                ('usd_rate', models.FloatField()),
                ('eur_rate', models.FloatField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
