# Generated by Django 4.0.2 on 2022-02-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='base_currency',
        ),
    ]
